language: cpp
compiler: gcc
dist: trusty

before_install:
    -   sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    -   sudo apt-get update -qq

install:
    # C++17
    -   sudo apt-get install -qq g++-6
    -   sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    # Codecov
    -   sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
    -   sudo pip install codecov
    -   sudo apt-get install xorg-dev

script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   cmake --build . -- -j 4
